---
working_dir: ./docker/nas
auto_discovery:
  enabled: true
  depth: 1
  delete: true
external_secrets:
  CF_API_TOKEN: op://Homelab/doco-cd/CF_API_TOKEN
  GARAGE_ADMIN_TOKEN: op://Homelab/garage/ADMIN_TOKEN
  GARAGE_RPC_SECRET: op://Homelab/garage/RPC_SECRET
  GARAGE_UI_OIDC_CLIENT_ID: op://Homelab/garage/OIDC_CLIENT_ID
  GARAGE_UI_OIDC_CLIENT_SECRET: op://Homelab/garage/OIDC_CLIENT_SECRET
  UNIFI_API_KEY: op://Homelab/unifi/UNIFI_API_KEY
  ZOT_HTPASSWD: op://Homelab/zot/HTPASSWD
  ZOT_OIDC_CLIENT_ID: op://Homelab/zot/OIDC_CLIENT_ID
  ZOT_OIDC_CLIENT_SECRET: op://Homelab/zot/OIDC_CLIENT_SECRET
  ZOT_SESSION_ENCRYPT_KEY: op://Homelab/zot/SESSION_ENCRYPT_KEY
  ZOT_SESSION_HASH_KEY: op://Homelab/zot/SESSION_HASH_KEY
force_recreate: false
reconciliation:
  enabled: true
  interval: 3600
reference: refs/heads/main
webhook_filter: ^refs/heads/main$
