---
# yaml-language-server: $schema=https://schemas.bykaj.io/apps.emqx.io/emqx_v2beta1.json
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx
spec:
  image: emqx/emqx:5.10.0@sha256:d52de0cc26924f55a6438efd4f2f10de0add5e494f070e6e62a3f027e52e5f93
  config:
    data: |
      authentication {
        backend = "built_in_database"
        mechanism = "password_based"
        password_hash_algorithm {
            name = "bcrypt"
            salt_rounds = 10
        }
        user_id_type = "username"
        bootstrap_file = "/secret/bootstrap/users.json"
        bootstrap_type = "plain"
      }
      authorization {
        sources = [
          {
            enable = true
            type = "file"
            path = "/secret/bootstrap/acl_file"
          }
        ]
        no_match: "deny"
      }
      listeners.ssl.default {
        bind = "0.0.0.0:8883"
        ssl_options {
          certfile = "/secret/cert/tls.crt"
          keyfile = "/secret/cert/tls.key"
          gc_after_handshake = true
          handshake_timeout = 5s
        }
      }
  coreTemplate:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      replicas: 3
      envFrom:
        - secretRef:
            name: emqx-dashboard-secret
      extraVolumeMounts:
        - name: bootstrap
          mountPath: /secret/bootstrap
          readOnly: true
        - name: emqx-tls
          mountPath: /secret/cert
          readOnly: true
      extraVolumes:
        - name: bootstrap
          secret:
            secretName: emqx-bootstrap-secret
        - name: emqx-tls
          secret:
            secretName: "${DOMAIN_IO/./-}-tls"
  listenersServiceTemplate:
    metadata:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "mqtt.${DOMAIN_IO}"
        lbipam.cilium.io/ips: 10.73.10.201
    spec:
      type: LoadBalancer