---
# yaml-language-server: $schema=https://schemas.bykaj.io/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
spec:
  chartRef:
    kind: OCIRepository
    name: rook-ceph-cluster
  interval: 1h
  timeout: 15m
  values:
    cephClusterSpec:
      cephConfig:
        global:
          bdev_enable_discard: "true" # quote
          bdev_async_discard_threads: "1" # quote
          osd_class_update_on_start: "false" # quote
          device_failure_prediction_mode: local # requires mgr module
          mon_data_avail_warn: "10" # quote
        mgr:
          log_max_recent: "100" # quote
        mon:
          mon_cluster_log_level: info
        osd:
          bluestore_slow_ops_warn_threshold: "50" # quote
          bluestore_slow_ops_warn_lifetime: "300"
      cleanupPolicy:
        wipeDevicesFromOtherClusters: true
      crashCollector:
        disable: false
      csi:
        readAffinity:
          enabled: false # https://github.com/ceph/ceph-csi/issues/5772
      dashboard:
        enabled: true
        urlPrefix: /
        ssl: false
        prometheusEndpoint: http://prometheus-operated.observability.svc.cluster.local:9090
      healthCheck:
        muteHealthWarning:
          AUTH_INSECURE_ROTATING_SERVICE_KEY_TYPE:
            policy: mute
          AUTH_INSECURE_CLIENT_KEY_TYPE:
            policy: mute
          AUTH_INSECURE_KEYS_ALLOWED:
            policy: mute
          AUTH_INSECURE_KEYS_CREATABLE:
            policy: mute
        livenessProbe:
          mon:
            probe:
              initialDelaySeconds: 30
              periodSeconds: 30
              timeoutSeconds: 10
          mgr:
            probe:
              initialDelaySeconds: 30
              periodSeconds: 30
              timeoutSeconds: 10
          osd:
            probe:
              initialDelaySeconds: 30
              periodSeconds: 30
              timeoutSeconds: 10
        startupProbe:
          mon:
            probe:
              initialDelaySeconds: 15
              periodSeconds: 30
              timeoutSeconds: 10
          mgr:
            probe:
              initialDelaySeconds: 15
              periodSeconds: 30
              timeoutSeconds: 10
          osd:
            probe:
              initialDelaySeconds: 15
              periodSeconds: 30
              timeoutSeconds: 10
      mgr:
        modules:
          - name: diskprediction_local
            enabled: true
          - name: insights
            enabled: true
          - name: pg_autoscaler
            enabled: true
          - name: rook
            enabled: true
      network:
        connections:
          requireMsgr2: true
      placement:
        all:
          tolerations:
            - key: tuppr.home-operations.com/outdated
              operator: Exists
        osd:
          tolerations:
            - key: tuppr.home-operations.com/outdated
              operator: Exists
              effect: PreferNoSchedule
      resources:
        mgr:
          limits:
            cpu: 500m
            memory: 720Mi
          requests:
            cpu: 50m
            memory: 360Mi
        mon:
          limits:
            cpu: 500m
            memory: 640Mi
          requests:
            cpu: 100m
            memory: 320Mi
        osd:
          limits:
            cpu: 500m
            memory: 8Gi
          requests:
            cpu: 150m
            memory: 1Gi
        prepareosd:
          limits:
            cpu: 1000m
            memory: 400Mi
          requests:
            cpu: 50m
            memory: 200Mi
        mgr-sidecar:
          limits:
            cpu: 256m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 40Mi
        crashcollector:
          limits:
            cpu: 100m
            memory: 64M
          requests:
            cpu: 15m
            memory: 32M
        logcollector:
          limits:
            cpu: 50m
            memory: 32Mi
          requests:
            cpu: 5m
            memory: 16Mi
        cleanup:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 100Mi
      security:
        cephx:
          daemon:
            keyRotationPolicy: KeyGeneration
            keyGeneration: 2
          csi:
            keyType: aes # aes256k requires kernel 7.0+
      storage:
        useAllNodes: false
        useAllDevices: false
        nodes:
          - name: k8s-01
            devicePathFilter: "^/dev/disk/by-id/nvme-Viper_VP4000M_500GB_.*"
          - name: k8s-02
            devicePathFilter: "^/dev/disk/by-id/nvme-Viper_VP4000M_500GB_.*"
          - name: k8s-03
            devicePathFilter: "^/dev/disk/by-id/nvme-PC801_NVMe_SK_hynix_1TB_.*"
    monitoring:
      enabled: true
      createPrometheusRules: true
      prometheusRuleOverrides:
        CephNodeInconsistentMTU:
          disabled: true
    toolbox:
      enabled: true
    route:
      dashboard:
        host:
          name: rook.bykaj.app
          path: /
          pathType: PathPrefix
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
    cephBlockPools:
      - name: ceph-blockpool
        spec:
          failureDomain: host
          replicated:
            size: 3
        storageClass:
          enabled: true
          name: ceph-block
          allowVolumeExpansion: true
          isDefault: true
          mountOptions:
            - discard
          parameters:
            compression_algorithm: zstd
            compression_mode: passive
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/controller-publish-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/controller-publish-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
            csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
            imageFeatures: deep-flatten,exclusive-lock,fast-diff,layering,object-map
            imageFormat: "2"
          reclaimPolicy: Delete
          volumeBindingMode: Immediate
    cephBlockPoolsVolumeSnapshotClass:
      enabled: true
      name: csi-ceph-blockpool
      deletionPolicy: Delete
      isDefault: true
    cephFileSystems: []
    cephObjectStores: []
