---
# yaml-language-server: $schema=https://schemas.bykaj.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app windshift
spec:
  components:
    - ../../../../components/kopiur/backup
    - ../../../../components/postgres
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  healthCheckExprs:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
  interval: 1h
  path: ./kubernetes/apps/default/windshift/app
  postBuild:
    substitute:
      APP: *app
      APP_NAME: Windshift
      APP_SUBDOMAIN: projects
      KOPIUR_CAPACITY: 10Gi
      POSTGRES_BACKUP_SCHEDULE: "54 0 * * *"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
