---
# yaml-language-server: $schema=https://schemas.bykaj.io/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mailkeep
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mailkeep-secret
    creationPolicy: Owner
    template:
      data:
        MAILKEEP__ENCRYPTION_SECRET: "{{ .MK_ENCRYPTION_SECRET }}"
  dataFrom:
    - extract:
        key: mailkeep
      rewrite: [{ regexp: { source: (.*), target: MK_$1 } }]
