---
# yaml-language-server: $schema=https://schemas.bykaj.io/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mailkeep
spec:
  chartRef:
    kind: OCIRepository
    name: mailkeep
  interval: 1h
  values:
    controllers:
      mailkeep:
        annotations:
          secret.reloader.stakater.com/reload: mailkeep-secret
        pod:
          labels:
            egress.policy.home.arpa/internet: "true"
          securityContext:
            fsGroup: 4000
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 4000
            runAsNonRoot: true
            runAsUser: 4000
        containers:
          app:
            image:
              repository: ghcr.io/szinn/mailkeep
              tag: v0.1.12@sha256:3993054bfb235276b21754bbd3a036810ee7952b2b4a33d63b7b46da252c8e62
            env:
              MAILKEEP__FRONTEND__BASE_URL: "https://mailkeep.bykaj.app"
              MAILKEEP__METADATA_PATH: /data
              MAILKEEP__STORAGE_PATH: /storage
              RUST_LOG: INFO
              TZ: ${TIMEZONE}
            envFrom:
              - secretRef:
                  name: mailkeep-secret
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: &port 8080
                  failureThreshold: 3
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /readyz
                    port: *port
                  failureThreshold: 3
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
    persistence:
      data:
        existingClaim: mailkeep
        globalMounts:
          - path: /data
      storage:
        type: nfs
        server: ${NAS_HOST}
        path: /mnt/vault/Backups/Apps/MailKeep
        globalMounts:
          - path: /storage
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
    route:
      app:
        hostnames:
          - mailkeep.bykaj.app
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      app:
        ports:
          http:
            port: *port
