---
# yaml-language-server: $schema=https://schemas.bykaj.io/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "bykaj-app"
spec:
  secretName: "bykaj-app-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "bykaj.app"
  dnsNames: ["bykaj.app", "*.bykaj.app"]
---
# yaml-language-server: $schema=https://schemas.bykaj.io/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "bykaj-dev"
spec:
  secretName: "bykaj-dev-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "bykaj.dev"
  dnsNames: ["bykaj.dev", "*.bykaj.dev"]
---
# yaml-language-server: $schema=https://schemas.bykaj.io/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "coder-bykaj-dev"
spec:
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "development"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  secretName: "coder-bykaj-dev-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "coder.bykaj.dev"
  dnsNames: ["coder.bykaj.dev", "*.coder.bykaj.dev"]
---
# yaml-language-server: $schema=https://schemas.bykaj.io/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "cetana-id"
spec:
  secretName: "cetana-id-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "cetana.id"
  dnsNames: ["cetana.id", "*.cetana.id"]
---
# yaml-language-server: $schema=https://schemas.bykaj.io/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "bykaj-io"
spec:
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "database"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  secretName: "bykaj-io-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "bykaj.io"
  dnsNames: ["bykaj.io", "*.bykaj.io"]
---
# yaml-language-server: $schema=https://schemas.bykaj.io/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "drup-lol"
spec:
  secretName: "drup-lol-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "drup.lol"
  dnsNames: ["drup.lol", "*.drup.lol"]
---
# yaml-language-server: $schema=https://schemas.bykaj.io/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "kaj-pics"
spec:
  secretName: "kaj-pics-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "kaj.pics"
  dnsNames: ["kaj.pics", "*.kaj.pics"]
