---
# yaml-language-server: $schema=https://schemas.bykaj.io/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: "bykaj-app-tls"
spec:
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: "bykaj-app-tls"
  template:
    data:
      tls.crt: '{{ index . "tls.crt" | b64enc }}'
      tls.key: '{{ index . "tls.key" | b64enc }}'
  data:
    - match:
        secretKey: &key tls.crt
        remoteRef:
          remoteKey: "bykaj-app-tls"
          property: *key
    - match:
        secretKey: &key tls.key
        remoteRef:
          remoteKey: "bykaj-app-tls"
          property: *key
---
# yaml-language-server: $schema=https://schemas.bykaj.io/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: "bykaj-dev-tls"
spec:
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: "bykaj-dev-tls"
  template:
    data:
      tls.crt: '{{ index . "tls.crt" | b64enc }}'
      tls.key: '{{ index . "tls.key" | b64enc }}'
  data:
    - match:
        secretKey: &key tls.crt
        remoteRef:
          remoteKey: "bykaj-dev-tls"
          property: *key
    - match:
        secretKey: &key tls.key
        remoteRef:
          remoteKey: "bykaj-dev-tls"
          property: *key
---
# yaml-language-server: $schema=https://schemas.bykaj.io/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: "coder-bykaj-dev-tls"
spec:
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: "coder-bykaj-dev-tls"
  template:
    data:
      tls.crt: '{{ index . "tls.crt" | b64enc }}'
      tls.key: '{{ index . "tls.key" | b64enc }}'
  data:
    - match:
        secretKey: &key tls.crt
        remoteRef:
          remoteKey: "coder-bykaj-dev-tls"
          property: *key
    - match:
        secretKey: &key tls.key
        remoteRef:
          remoteKey: "coder-bykaj-dev-tls"
          property: *key
---
# yaml-language-server: $schema=https://schemas.bykaj.io/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: "cetana-id-tls"
spec:
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: "cetana-id-tls"
  template:
    data:
      tls.crt: '{{ index . "tls.crt" | b64enc }}'
      tls.key: '{{ index . "tls.key" | b64enc }}'
  data:
    - match:
        secretKey: &key tls.crt
        remoteRef:
          remoteKey: "cetana-id-tls"
          property: *key
    - match:
        secretKey: &key tls.key
        remoteRef:
          remoteKey: "cetana-id-tls"
          property: *key
---
# yaml-language-server: $schema=https://schemas.bykaj.io/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: "bykaj-io-tls"
spec:
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: "bykaj-io-tls"
  template:
    data:
      tls.crt: '{{ index . "tls.crt" | b64enc }}'
      tls.key: '{{ index . "tls.key" | b64enc }}'
  data:
    - match:
        secretKey: &key tls.crt
        remoteRef:
          remoteKey: "bykaj-io-tls"
          property: *key
    - match:
        secretKey: &key tls.key
        remoteRef:
          remoteKey: "bykaj-io-tls"
          property: *key
---
# yaml-language-server: $schema=https://schemas.bykaj.io/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: "drup-lol-tls"
spec:
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: "drup-lol-tls"
  template:
    data:
      tls.crt: '{{ index . "tls.crt" | b64enc }}'
      tls.key: '{{ index . "tls.key" | b64enc }}'
  data:
    - match:
        secretKey: &key tls.crt
        remoteRef:
          remoteKey: "drup-lol-tls"
          property: *key
    - match:
        secretKey: &key tls.key
        remoteRef:
          remoteKey: "drup-lol-tls"
          property: *key
---
# yaml-language-server: $schema=https://schemas.bykaj.io/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: "kaj-pics-tls"
spec:
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: "kaj-pics-tls"
  template:
    data:
      tls.crt: '{{ index . "tls.crt" | b64enc }}'
      tls.key: '{{ index . "tls.key" | b64enc }}'
  data:
    - match:
        secretKey: &key tls.crt
        remoteRef:
          remoteKey: "kaj-pics-tls"
          property: *key
    - match:
        secretKey: &key tls.key
        remoteRef:
          remoteKey: "kaj-pics-tls"
          property: *key
