---
# yaml-language-server: $schema=https://schemas.bykaj.io/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: robusta
spec:
  chart:
    spec:
      chart: robusta
      version: 0.29.0
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: robusta
  interval: 1h
  values:
    clusterName: homelab
    globalConfig:
      signing_key: "{{ env.SIGNING_KEY }}"
      account_id: "{{ env.ACCOUNT_ID }}"
    sinksConfig:
      - robusta_sink:
          name: robusta_ui_sink
          token: "{{ env.SINK_TOKEN }}"
    enablePrometheusStack: false
    enablePlatformPlaybooks: true
    runner:
      sendAdditionalTelemetry: true
      additional_env_vars:
        - name: ACCOUNT_ID
          valueFrom:
            secretKeyRef:
              name: &secret robusta-secret
              key: ACCOUNT_ID
        - name: SIGNING_KEY
          valueFrom:
            secretKeyRef:
              name: *secret
              key: SIGNING_KEY
        - name: SINK_TOKEN
          valueFrom:
            secretKeyRef:
              name: *secret
              key: SINK_TOKEN
    enableHolmesGPT: true
    enabledManagedConfiguration: true
    holmes:
      additionalEnvVars:
        - name: ROBUSTA_AI
          value: "true"
        - name: ACCOUNT_ID
          valueFrom:
            secretKeyRef:
              name: *secret
              key: ACCOUNT_ID
        - name: SIGNING_KEY
          valueFrom:
            secretKeyRef:
              name: *secret
              key: SIGNING_KEY
        - name: SINK_TOKEN
          valueFrom:
            secretKeyRef:
              name: *secret
              key: SINK_TOKEN

