---
# yaml-language-server: $schema=https://schemas.bykaj.io/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app oidc-provider-debugger
spec:
  chartRef:
    kind: OCIRepository
    name: oidc-provider-debugger
  interval: 1h
  values:
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: leplusorg/openid-connect-provider-debugger
              tag: 1.27.1-2@sha256:3f5a18cec6e1590b8833a36a659fe64280ae8019c3af2eb8104df58a2160d216
            env:
              oidc_redirect_uri: "https://${APP_DOMAIN:=${APP_SUBDOMAIN:=${APP}}.${DOMAIN_APP}}/login"
              oidc_scope: "openid profile email"
              oidc_post_logout_uri: "https://${APP_DOMAIN:=${APP_SUBDOMAIN:=${APP}}.${DOMAIN_APP}}/status"
            envFrom:
              - secretRef:
                  name: oidc-provider-debugger-secret
    persistence:
      config:
        type: configMap
        name: oidc-provider-debugger-config
        globalMounts:
          - path: /etc/nginx/conf.d/default.conf
            subPath: default.conf
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
    route:
      *app :
        hostnames:
          - "${APP_DOMAIN:=${APP_SUBDOMAIN:=${APP}}.${DOMAIN_APP}}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: *app
                port: &port 80
    service:
      *app :
        controller: *app
        ports:
          http:
            port: *port
