---
# yaml-language-server: $schema=https://schemas.bykaj.io/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nutify
spec:
  chartRef:
    kind: OCIRepository
    name: nutify
  interval: 1h
  values:
    controllers:
      nutify:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: dartsteven/nutify
              tag: amd64-0.1.7@sha256:9ba50751b8776f0bb3046650369ae2dab4788098ba1aca34fbef2f361164a41d
            env:
              TZ: "${TIMEZONE}"
            envFrom:
              - secretRef:
                  name: nutify-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 5050
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: true
              readOnlyRootFilesystem: false
              capabilities:
                add:
                  - SYS_ADMIN
            resources:
              requests:
                cpu: 15m
                memory: 384Mi
              limits:
                memory: 512Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    persistence:
      config:
        existingClaim: "${VOLSYNC_CLAIM:=${APP}}"
        globalMounts:
          - path: /app/nutify/instance
            subPath: instance
          - path: /app/ssl
            subPath: ssl
          - path: /etc/nut
            subPath: etc/nut
      backups:
        type: nfs
        server: "${NAS_HOST}"
        path: /mnt/vault-alpha/Backups
        globalMounts:
          - path: /mnt/backups
            subPath: Apps/Nutify
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
          - path: /app/nutify/logs
            subPath: logs
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: "Tools"
          gethomepage.dev/name: "${APP_NAME}"
          gethomepage.dev/icon: "sh-nutify.png"
        hostnames:
          - "${APP_DOMAIN:=${APP_SUBDOMAIN:=${APP}}.${DOMAIN_APP}}"
        parentRefs:
          - name: envoy-internal
            namespace: network
