---
# yaml-language-server: $schema=https://schemas.bykaj.io/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-mcp
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: litellm-mcp-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        HOMEASSISTANT_URL: "{{ .LL_HOMEASSISTANT_URL }}"
        HOMEASSISTANT_TOKEN: "{{ .LL_HOMEASSISTANT_TOKEN }}"
  dataFrom:
    - extract:
        key: litellm
      rewrite: [{ regexp: { source: (.*), target: LL_$1 } }]
