---
# yaml-language-server: $schema=https://schemas.bykaj.io/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zitadel
spec:
  interval: 1h
  chart:
    spec:
      chart: zitadel
      version: 9.2.0
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: zitadel
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  # Default values
  # Ref: https://github.com/zitadel/zitadel-charts/blob/main/charts/zitadel/values.yaml
  values:
    annotations:
      reloader.stakater.com/auto: "true"

    replicaCount: 1

    zitadel:
      # configmapConfig & secretConfig
      # Ref: https://github.com/zitadel/zitadel/blob/main/cmd/defaults.yaml
      configmapConfig:
        Log:
          Level: info
          Formatter:
            Format: text

        Metrics:
          Type: otel

        Telemetry:
          Enabled: false

        ExternalDomain: "${GATUS_DOMAIN:=${GATUS_SUBDOMAIN:=${APP}}.${DOMAIN_APP}}"
        ExternalPort: 443
        ExternalSecure: true
        TLS:
          Enabled: false
        Port: 8080

        Database:
          Postgres:
            Host: "${DB_HOST}"
            Port: 5432
            MaxOpenConns: 10
            MaxIdleConns: 5
            MaxConnLifetime: 30m
            MaxConnIdleTime: 5m
            User:
              SSL:
                Mode: disable
            Admin:
              SSL:
                Mode: disable

        Caches:
          Connectors:
            Memory:
              Enabled: false
            Postgres:
              Enabled: true
            Redis:
              Enabled: false
              Addr: "${REDIS_HOST}:6379"
              DBOffset: 10
          # Instance:
          #   Connector: "redis"
          # Milestones:
          #   Connector: "redis"
          # Organization:
          #   Connector: "redis"
          IdPFormCallbacks:
            Connector: "postgres"
          FederatedLogouts:
            Connector: "postgres"

        FirstInstance:
          InstanceName: &instanceName "Cetana ID"
          DefaultLanguage: en
          Org:
            Name: "ByKaj"
            Human:
              FirstName: "Apps"
              LastName: "Admin"
              Email:
                Verified: true
          LoginPolicy:
            AllowRegister: false
            AllowExternalIDP: false
            ForceMFA: true
          LabelPolicy:
            PrimaryColor: "#5469d4"
            BackgroundColor: "#fafafa"
            WarnColor: "#cd3d56"
            FontColor: "#000000"
            PrimaryColorDark: "#2073c4"
            BackgroundColorDark: "#111827"
            WarnColorDark: "#ff3b5b"
            FontColorDark: "#ffffff"
            HideLoginNameSuffix: false
            ErrorMsgPopup: false
            DisableWatermark: false
          LockoutPolicy:
            MaxPasswordAttempts: 3
            MaxOTPAttempts: 3
          PrivacyPolicy:
            CustomLink: "https://status.${DOMAIN_APP}"
            CustomLinkText: "Service Status"

        DefaultInstance:
          DefaultLanguage: en
          LockoutPolicy:
            MaxPasswordAttempts: 3
            MaxOTPAttempts: 3
          LoginPolicy:
            AllowRegister: false
            AllowExternalIDP: false
            ForceMFA: true
          PrivacyPolicy:
            CustomLink: "https://status.${DOMAIN_APP}"
            CustomLinkText: "Service Status"
          SMTPConfiguration:
            TLS: true
            FromName: *instanceName

        ServicePing:
          Enabled: false

      configSecretName: &secret zitadel-secret
      configSecretKey: config-yaml

      masterkeySecretName: *secret

    ingress:
      enabled: false

    login:
      ingress:
        enabled: false
      resources: {}

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        honorLabels: false
        honorTimestamps: true

    pdb:
      enabled: false
      minAvailable: 1

    resources: {}
