---
# yaml-language-server: $schema=https://schemas.bykaj.io/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nut-exporter
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: nut-exporter-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        NUT_EXPORTER_USERNAME: "{{ .NE_NUT_EXPORTER_USERNAME }}"
        NUT_EXPORTER_PASSWORD: "{{ .NE_NUT_EXPORTER_PASSWORD }}"
  dataFrom:
    - extract:
        key: nut-exporter
      rewrite: [{ regexp: { source: (.*), target: NE_$1 } }]
