---
# yaml-language-server: $schema=https://schemas.bykaj.io/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nut-exporter-ups-2u
  labels:
    app.kubernetes.io/component: nut-exporter
    app.kubernetes.io/instance: ups-2u
    app.kubernetes.io/name: nut-exporter
spec:
  endpoints:
    - metricRelabelings:
        - action: replace
          replacement: ups-2u
          targetLabel: instance
        # - action: replace
        #   replacement: rak
        #   targetLabel: ups
        - action: labeldrop
          regex: (pod)
      params:
        ups:
          - ups
        server:
          - 10.73.0.50
      path: /ups_metrics
      port: metrics
      scheme: http
  jobLabel: app.kubernetes.io/instance
  namespaceSelector:
    matchNames:
      - observability
  selector:
    matchLabels:
      app.kubernetes.io/instance: nut-exporter
      app.kubernetes.io/name: nut-exporter
