---
# yaml-language-server: $schema=https://schemas.bykaj.io/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kguardian
spec:
  chartRef:
    kind: OCIRepository
    name: kguardian
  interval: 1h
  values:
    ai:
      baseUrl: http://litellm.ai.svc.cluster.local:4000/v1
      enabled: true
      mcp:
        auth:
          allowUnauthenticated: true
        enabled: true
      model: minimax/MiniMax-M2-7-anthropic
      provider: openai
      secret: kguardian-secret
    broker:
      resources:
        limits:
          memory: 2Gi
    database:
      persistence:
        storageClassName: openebs-hostpath
      resources:
        limits:
          memory: 1Gi
    frontend:
      allowedHosts:
        - kguardian.bykaj.app
    llmBridge:
      replicaCount: 1
    telemetry:
      enabled: false
