---
# yaml-language-server: $schema=https://schemas.bykaj.io/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: memini
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: memini-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        LITELLM_API_KEY: "{{ .LL_LITELLM_MASTER_KEY }}"
        MEMINI_API_KEY: "{{ .MM_MEMINI_API_KEY }}"
  dataFrom:
    - extract:
        key: memini
      rewrite: [{ regexp: { source: (.*), target: MM_$1 } }]
    - extract:
        key: litellm
      rewrite: [{ regexp: { source: (.*), target: LL_$1 } }]
