---
# yaml-language-server: $schema=https://schemas.bykaj.io/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mail-archiver
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mail-archiver-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        OAuth__AdminEmails__0: "{{ .MA_ADMIN_EMAIL }}"
        OAuth__ClientId: "{{ .MA_OIDC_CLIENT_ID }}"
        OAuth__ClientSecret: "{{ .MA_OIDC_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: mail-archiver
      rewrite: [{ regexp: { source: (.*), target: MA_$1 } }]
