---
# yaml-language-server: $schema=https://schemas.bykaj.io/gateway.envoyproxy.io/backend_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: doco-cd-webhook
spec:
  endpoints:
    - fqdn:
        hostname: doco-cd.bykaj.app
        port: 443
  tls:
    sni: doco-cd.bykaj.app
    wellKnownCACertificates: System
