---
# yaml-language-server: $schema=https://schemas.bykaj.io/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app pgadmin
spec:
  chartRef:
    kind: OCIRepository
    name: pgadmin
  interval: 1h
  values:
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: dpage/pgadmin4
              tag: 9.15.0@sha256:cefc4cc6b7d9d71a9e81e76fb9d7e14038ab5661b539a190eea1b63fa612589a
            env:
              PGADMIN_CONFIG_AUTHENTICATION_SOURCES: "['oauth2']"
              PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: "20"
              PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
              PGADMIN_CONFIG_MAIL_PORT: "587"
              PGADMIN_CONFIG_MAIL_USE_TLS: "True"
              PGADMIN_CONFIG_OAUTH2_AUTO_CREATE_USER: "True"
              PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: "False"
              PGADMIN_DISABLE_POSTFIX: "True"
              PGADMIN_LISTEN_PORT: &port 5050
            envFrom:
              - secretRef:
                  name: pgadmin-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /misc/ping
                    port: *port
                  initialDelaySeconds: 20
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsUser: ${APP_UID:=5050}
        runAsGroup: ${APP_GID:=5050}
        fsGroup: ${APP_GID:=5050}
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        existingClaim: "${KOPIUR_CLAIM:=${APP}}"
        globalMounts:
          - path: /var/lib/pgadmin
      backups:
        type: nfs
        server: "${NAS_HOST}"
        path: /mnt/vault/Backups/Apps
        globalMounts:
          - path: /mnt/backups
            subPath: pgAdmin
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: "Tools"
          gethomepage.dev/name: "${APP_NAME}"
          gethomepage.dev/icon: "sh-pgadmin.svg"
        hostnames:
          - "${APP_DOMAIN:=${APP_SUBDOMAIN:=${APP}}.bykaj.app}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - name: *app
                port: *port
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
