---
# yaml-language-server: $schema=https://schemas.bykaj.io/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plex
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: plex-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Database Init
        INIT_POSTGRES_HOST: "${DB_HOST}"
        INIT_POSTGRES_DBNAME: "{{ .IM_POSTGRES_DB }}"
        INIT_POSTGRES_USER: "{{ .IM_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .IM_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_USER: "{{ .PG_POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .PG_POSTGRES_SUPER_PASS }}"
        # App Configuration
        DB_URL: "postgres://{{ .IM_POSTGRES_USER }}:{{ .IM_POSTGRES_PASSWORD }}@${DB_HOST}:5432/{{ .IM_POSTGRES_DB }}?sslmode=disable"
        REDIS_PASSWORD: "{{ .DF_DRAGONFLY_PASSWORD }}"
  dataFrom:
    - extract:
        key: immich
      rewrite: [{regexp: {source: (.*), target: IM_$1}}]
    - extract:
        key: dragonfly
      rewrite: [{regexp: {source: (.*), target: DF_$1}}]
    - extract:
        key: cloudnative-pg
      rewrite: [{regexp: {source: (.*), target: PG_$1}}]
