---
# yaml-language-server: $schema=https://schemas.bykaj.io/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  chartRef:
    kind: OCIRepository
    name: immich
  interval: 1h
  values:
    defaultPodOptions:
      enableServiceLinks: false
      securityContext:
        fsGroup: 4000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 4000
        runAsNonRoot: true
        runAsUser: 4000
    controllers:
      immich:
        annotations:
          reloader.stakater.com/auto: "true"
        # initContainers:
        #   init-db:
        #     image:
        #       repository: ghcr.io/home-operations/postgres-init
        #       tag: 18.6@sha256:b6d3af974df781c673d37e49bdddfa14a6f5be28b18d2cb7713f0449bea4057b
        #     envFrom: &envFrom
        #       - secretRef:
        #           name: immich-secret
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v3.1.0@sha256:b434cb9287eea1471c9974845914d4dd328c9c2d652e446ed4930f99944f0ceb
            env:
              IMMICH_ALLOW_SETUP: "false"
              IMMICH_MEDIA_LOCATION: &mediaLocation /data
              IMMICH_TELEMETRY_INCLUDE: "all"
              IMMICH_WORKERS_INCLUDE: "api"
              REDIS_DBINDEX: "5"
              REDIS_HOSTNAME: "${REDIS_HOST}"
              TZ: "${TIMEZONE}"
            envFrom:
              - secretRef:
                  name: immich-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  failureThreshold: 5
                  httpGet:
                    path: /server-info/ping
                    port: &port 2283
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  failureThreshold: 30
                  httpGet:
                    path: /api/server/ping
                    port: *port
                  periodSeconds: 5
                  successThreshold: 1
                  timeoutSeconds: 1
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
              readOnlyRootFilesystem: true
    persistence:
      backups:
        type: nfs
        path: /mnt/vault/Backups
        server: "${NAS_HOST}"
        globalMounts:
          - path: /data/backups
            subPath: Apps/Immich
      library:
        type: nfs
        path: /mnt/vault/Photos/Library
        server: "${NAS_HOST}"
        globalMounts:
          - path: *mediaLocation
      import:
        type: nfs
        path: /mnt/vault/Photos/Import
        server: "${NAS_HOST}"
        globalMounts:
          - path: /import
      tmpfs:
        type: emptyDir
        advancedMounts:
          immich:
            app:
              - path: /usr/src/app/.reverse-geocoding-dump
                subPath: geocoding
              - path: /usr/src/app/.transformers_cache
                subPath: transformers
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == 200"]
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: "Media"
          gethomepage.dev/icon: "sh-immich.svg"
          gethomepage.dev/name: "${APP_NAME}"
        hostnames:
          - "${APP_DOMAIN:=${APP_SUBDOMAIN:=${APP}}.bykaj.app}"
        parentRefs:
          - name: envoy-external
            namespace: network
    service:
      immich:
        controller: immich
        ports:
          http:
            port: *port
          metrics-api:
            port: 8081
          metrics-ms:
            port: 8082
    serviceMonitor:
      immich:
        enabled: true
        endpoints:
          - path: /metrics
            port: metrics-api
            scheme: http
          - path: /metrics
            port: metrics-ms
            scheme: http
        serviceName: immich
