{
 "title": "Control Plane",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Replicas",
   "type": "stat",
   "description": "One or more replicas are required to be running in order to serve the control-plane.\n\nSee High Availability for details on how to run multiple coderd replicas.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{pod=~`coder.*`, pod!~`.*provisioner.*`, namespace=`development`} == 1) or vector(0)",
     "legendFormat": "Up"
    },
    {
     "expr": "(count(up{pod=~`coder.*`, pod!~`.*provisioner.*`, namespace=`development`} == 0) or vector(0)) > 0",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "Terminations",
   "type": "timeseries",
   "description": "\n\nPods can be terminated for several reasons:\n\nOOMKilled: pod exceeded its defined memory limit or was terminated by the OS for using excessive memory (if no limit defined)\nError: usually attributeable to a configuration problem\nEvicted: pod has been evicted from node for overusing resources and will be rescheduled on another node is possible",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (reason) (\n  count_over_time(kube_pod_container_status_terminated_reason{pod=~`coder.*`, pod!~`.*provisioner.*`, namespace=`development`}[$__interval])\n)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{pod=~`coder.*`, pod!~`.*provisioner.*`, namespace=`development`}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage Seconds",
   "type": "timeseries",
   "description": "The cumulative CPU used per core-second. If coderd was using a full CPU core, that would be represented as 1 second.\n\nRequests & limits are shown if set.",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{pod=~`coder.*`, pod!~`.*provisioner.*`, namespace=`development`}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{pod=~`coder.*`, pod!~`.*provisioner.*`, namespace=`development`, resource=\"cpu\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{pod=~`coder.*`, pod!~`.*provisioner.*`, namespace=`development`, resource=\"cpu\"})",
     "legendFormat": "Requested"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "description": "This shows the total memory used by each coderd container; it is the same metric which the OOM killer uses.\n\nRequests & limits are shown if set.",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (pod) (container_memory_working_set_bytes{pod=~`coder.*`, pod!~`.*provisioner.*`, namespace=`development`})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{pod=~`coder.*`, pod!~`.*provisioner.*`, namespace=`development`, resource=\"memory\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{pod=~`coder.*`, pod!~`.*provisioner.*`, namespace=`development`, resource=\"memory\"})",
     "legendFormat": "Requested"
    }
   ]
  },
  {
   "title": "API Requests",
   "type": "timeseries",
   "description": "This shows the number of requests per second each coderd replica is handling.\n\nHeavy skewing towards a single coderd replica indicates faulty loadbalancing.",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(coderd_api_requests_processed_total{pod=~`coder.*`, pod!~`.*provisioner.*`, namespace=`development`}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pubsub Latency (Median)",
   "type": "stat",
   "description": "coderd uses Postgres for passing messages between subcomponents for coordination and signalling; this is called \"pubsub\" (or publish-subscribe).\n\nWe measure the time for messages to be sent and received. Latencies higher than 500ms will likely lead to your Coder deployment feeling sluggish. High latency is usually an indication that your Postgres server is under-resourced on CPU.\n\nHigh values for median should be concerning, while the 90th percentile shows the outliers.",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "quantile(0.5, coder_pubsub_send_latency_seconds)",
     "legendFormat": "Send"
    },
    {
     "expr": "quantile(0.5, coder_pubsub_receive_latency_seconds)",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Pubsub Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n  sum(increase(coder_pubsub_latency_measure_errs_total[$__range]))\n  / count(coder_pubsub_latency_measure_errs_total)\n) or vector(0)",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Pubsub Latency (P90)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "quantile(0.9, coder_pubsub_send_latency_seconds)",
     "legendFormat": "Send"
    },
    {
     "expr": "quantile(0.9, coder_pubsub_receive_latency_seconds)",
     "legendFormat": "Receive"
    }
   ]
  }
 ]
}