{
 "title": "Status",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Coder Replicas",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{pod=~`coder.*`, pod!~`.*provisioner.*`, namespace=`development`} == 1) or vector(0) > 0",
     "legendFormat": "Up"
    },
    {
     "expr": "count(up{pod=~`coder.*`, pod!~`.*provisioner.*`, namespace=`development`} == 0) or vector(0) > 0",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "Provisioners",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(coderd_provisionerd_num_daemons{pod=~`coder.*`, pod!~`.*provisioner.*`, namespace=`development`})",
     "legendFormat": "Built-in"
    },
    {
     "expr": "sum(coderd_provisionerd_num_daemons{pod=~`coder-provisioner.*`, namespace=`development`})",
     "legendFormat": "External"
    }
   ]
  },
  {
   "title": "Workspace Builds",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum by (status) (increase(coderd_provisionerd_job_timings_seconds_count{pod!=``}[$__range])))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Running Workspaces",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_ready{condition=\"true\", namespace=`coder-workspaces`} == 1)\nor\ncount(coderd_api_workspace_latest_build{status=\"running\"})\nor\nvector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Usage High Watermark (Cumulative)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    max_over_time(\n        rate(container_cpu_usage_seconds_total{pod=~`coder.*`, pod!~`.*provisioner.*`, namespace=`development`}[1h:1m])\n        [$__range:]\n    )\n)",
     "legendFormat": "Control Plane CPU"
    },
    {
     "expr": "sum(\n    max_over_time(\n        rate(container_cpu_usage_seconds_total{pod=~`coder-provisioner.*`, namespace=`development`}[1h:1m])\n        [$__range:]\n    )\n)",
     "legendFormat": "Provisioner CPU"
    },
    {
     "expr": "sum(\n    max_over_time(\n        container_memory_working_set_bytes{pod=~`coder.*`, pod!~`.*provisioner.*`, namespace=`development`}\n        [$__range:]\n    )\n)",
     "legendFormat": "Control Plane RAM"
    },
    {
     "expr": "sum(\n    max_over_time(\n        container_memory_working_set_bytes{pod=~`coder-provisioner.*`, namespace=`development`}\n        [$__range:]\n    )\n)",
     "legendFormat": "Provisioner RAM"
    }
   ]
  }
 ]
}