---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
data:
  # Servers
  MQTT_HOST: emqx-headless.database.svc.cluster.local
  NAS_HOST: nas.internal
  # Network CIDRs
  LAN_CIDR: 10.73.0.0/20
  POD_CIDR: 10.42.0.0/16
  SERVICE_CIDR: 10.43.0.0/16
  TAILSCALE_CIDR: 100.64.0.0/10
  # Reserved IPs for LoadBalancer services
  LB_IP_PLEX: 10.73.20.200
  LB_IP_EMQX: 10.73.20.201
  LB_IP_CODER: 10.73.20.203
  LB_IP_JELLYFIN: 10.73.20.204
