---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
data:
  # Settings
  TIMEZONE: Europe/Amsterdam
  # Servers
  DB_HOST: postgres-rw.database.svc.cluster.local
  MQTT_HOST: emqx-headless.database.svc.cluster.local
  NAS_HOST: nas.home.cetana.net
  REDIS_HOST: dragonfly.database.svc.cluster.local
  # Network CIDRs
  LAN_CIDR: 10.73.0.0/20
  POD_CIDR: 10.42.0.0/16
  SERVICE_CIDR: 10.43.0.0/16
  TAILSCALE_CIDR: 100.64.0.0/10
  # Reserved IPs for LoadBalancer services
  LB_IP_PLEX: 10.73.10.200
  LB_IP_EMQX: 10.73.10.201
  LB_IP_POSTGRES: 10.73.10.202
  LB_IP_CODER: 10.73.10.203
  LB_IP_JELLYFIN: 10.73.10.204
