---
apiVersion: v1
kind: Namespace
metadata:
  name: not-used
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    goldilocks.fairwinds.com/enabled: "true"
    resource.kubernetes.io/admin-access: "true"
