---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/namespace
replacements:
  - path: ../../components/replacements/ks.yaml
resources:
  - ./atuin/ks.yaml
  - ./changedetection/ks.yaml
  - ./homepage/ks.yaml
  - ./it-tools/ks.yaml
  - ./karakeep/ks.yaml
  - ./kopia/ks.yaml
  - ./n8n/ks.yaml
  - ./nutify/ks.yaml
  - ./opencloud/ks.yaml
  - ./paperless/ks.yaml
  - ./pgadmin/ks.yaml
  - ./spoolman/ks.yaml
  - ./thelounge/ks.yaml
  - ./wallos/ks.yaml
  - ./wastebin/ks.yaml
