---
# yaml-language-server: $schema=https://schemas.bykaj.io/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: devices
spec:
  module: icmp
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - gw-adam.home.cetana.net
        - gw-anna.home.cetana.net
        - gw-hue.home.cetana.net
        - gw-sip.home.cetana.net
        - homeassistant.home.cetana.net
        - icarus.home.cetana.net
        - leonis.home.cetana.net
        - nas.home.cetana.net
        - security_system.home.cetana.net
        - zeus.home.cetana.net
---
# yaml-language-server: $schema=https://schemas.bykaj.io/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: nfs
spec:
  jobName: nfs_probe
  module: tcp_connect
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - ${NAS_HOST}:2049
---
# yaml-language-server: $schema=https://schemas.bykaj.io/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: smb
spec:
  jobName: smb_probe
  module: tcp_connect
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - ${NAS_HOST}:445
---
# yaml-language-server: $schema=https://schemas.bykaj.io/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: postgres
spec:
  jobName: postgres_probe
  module: tcp_connect
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - ${DB_HOST}:5432
---
# yaml-language-server: $schema=https://schemas.bykaj.io/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: redis
spec:
  jobName: redis_probe
  module: tcp_connect
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - ${REDIS_HOST}:6379
