---
# yaml-language-server: $schema=https://schemas.bykaj.io/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name calibre-web-automated
spec:
  chartRef:
    kind: OCIRepository
    name: calibre-web-automated
  interval: 1h
  values:
    controllers:
      *name :
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: Recreate
        containers:
          app:
            image:
              repository: docker.io/crocodilestick/calibre-web-automated
              tag: V3.1.4@sha256:577e846f104fd21453ef306eefb4a95dd95b3b9ddd2463a150944494284da0fd
            env:
              PGID: "${APP_GID}"
              PUID: "${APP_UID}"
              TZ: "${TIMEZONE}"
            envFrom:
              - secretRef:
                  name: calibre-web-automated-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /login
                    port: &port 8083
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: true  # because S6 overlay
              readOnlyRootFilesystem: false   # because S6 overlay
              capabilities:
                drop:
                  - ALL
                add:
                  # because S6 overlay
                  - CHOWN
                  - SETUID
                  - SETGID
                  - FOWNER
                  - DAC_OVERRIDE
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false   # because S6 overlay
        runAsUser: 0          # because S6 overlay
        runAsGroup: 0         # because S6 overlay
        seccompProfile: { type: RuntimeDefault }
    ingress:
      ts:
        className: tailscale
        hosts:
          - host: &host ${APP_SUBDOMAIN:=${APP}}.${TAILSCALE_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: *name
                  port: *port
        tls:
          - hosts:
              - *host
    persistence:
      backups:
        type: nfs
        server: "${NAS_HOST}"
        path: /mnt/vault-alpha/Backups
        advancedMounts:
          *name :
            app:
              - path: /config/processed_books
                subPath: Apps/Calibre-Web-Automated
      config:
        existingClaim: "${VOLSYNC_CLAIM:=${APP}}"
        advancedMounts:
          *name :
            app:
              - path: /config
      media:
        type: nfs
        server: "${NAS_HOST}"
        path: /mnt/vault-alpha/Media
        advancedMounts:
          *name :
            app:
              - path: /calibre-library
                subPath: Books/Ebooks/Library
              - path: /cwa-book-ingest
                subPath: Books/Ebooks/Import
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
            subPath: logs
          - path: /config/.cwa_conversion_tmp
            subPath: conversion
          - path: /tmp
            subPath: tmp
    route:
      *name :
        hostnames:
          - "${APP_DOMAIN:=${APP_SUBDOMAIN:=${APP}}.${DOMAIN_APP}}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: *name
                port: *port
    service:
      *name :
        controller: *name
        ports:
          http:
            port: *port

