---
# yaml-language-server: $schema=https://schemas.bykaj.io/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: configarr
spec:
  chartRef:
    kind: OCIRepository
    name: configarr
  interval: 1h
  values:
    controllers:
      configarr:
        type: cronjob
        annotations:
          reloader.stakater.com/auto: "true"
        cronjob:
          schedule: "0 0/12 * * *" # Runs every 12 hours
          timeZone: "${TIMEZONE}"
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
        containers:
          app:
            image:
              repository: ghcr.io/raydak-labs/configarr
              tag: 1.30.1@sha256:8c4f49180fe23eb3d41409efe065c3709c85a94410054e467e202242057bfb88
            env:
              TZ: "${TIMEZONE}"
            envFrom:
              - secretRef:
                  name: configarr-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 5m
                memory: 32Mi
              limits:
                memory: 128Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 4000
        runAsGroup: 4000
        fsGroup: 4000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        enabled: true
        type: configMap
        name: configarr-config
        globalMounts:
          - path: /app/config/config.yml
            subPath: config.yml
            readOnly: true
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /app/repos
            subPath: repos
