---
# yaml-language-server: $schema=https://schemas.bykaj.io/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  bootstrap:
    # initdb:
    #   database: app
    #   owner: app
    #   secret:
    #     name: cloudnative-pg-bootstrap-secret
    # Recovers from the latest S3 backup (after changing `serverName` in `ks.yaml`)
    recovery:
      source: postgres-backup
  # Ref: https://github.com/cloudnative-pg/cloudnative-pg/issues/2570
  enablePDB: false
  enableSuperuserAccess: true
  # Ref: https://www.beyondwatts.com/posts/debugging-barman-xamzcontentsha256mismatch-error-after-upgrading-to-postgresql175/
  env:
    - name: AWS_REQUEST_CHECKSUM_CALCULATION
      value: when_required
    - name: AWS_RESPONSE_CHECKSUM_VALIDATION
      value: when_required
  externalClusters:
    - name: postgres-backup
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: cloudnative-pg-b2
          serverName: ${CNPG_V18_PREVIOUS_CLUSTER}
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-system-trixie@sha256:9287ce030c6f3ce822e383b019ae4aaf1e8370bff3b39f9c51dc10d69dc97219
  instances: 3
  monitoring:
    enablePodMonitor: true
  plugins:
    - isWALArchiver: true
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: cloudnative-pg-b2
        serverName: ${CNPG_V18_CURRENT_CLUSTER}
  postgresql:
    parameters:
      max_connections: '300'
      pg_stat_statements.max: '10000'
      pg_stat_statements.track: all
      shared_buffers: 512MB
    synchronous:
      method: any
      number: 1
    extensions:
      - name: pgvector
        image:
          # renovate: suite=trixie-pgdg depName=postgresql-18-pgvector
          reference: ghcr.io/cloudnative-pg/pgvector:0.8.5-18-trixie
  primaryUpdateStrategy: unsupervised
  replicationSlots:
    highAvailability:
      enabled: true
    updateInterval: 30
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 80m
      memory: 768Mi
  storage:
    size: 20Gi
    storageClass: openebs-hostpath
  superuserSecret:
    name: cloudnative-pg-secret
