---
# yaml-language-server: $schema=https://schemas.bykaj.io/barmancloud.cnpg.io/objectstore_v1.json
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: cloudnative-pg-storj
spec:
  configuration:
    data:
      compression: bzip2
    destinationPath: "s3://cloudnative-pg"
    endpointURL: "https://gateway.storjshare.io"
    s3Credentials:
      accessKeyId:
        name: &secret cloudnative-pg-secret
        key: STORJ_ACCESS_KEY
      secretAccessKey:
        name: *secret
        key: STORJ_SECRET_KEY
    wal:
      compression: bzip2
      maxParallel: 8
  retentionPolicy: 30d
---
# yaml-language-server: $schema=https://schemas.bykaj.io/barmancloud.cnpg.io/objectstore_v1.json
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: cloudnative-pg-b2
spec:
  configuration:
    data:
      compression: bzip2
    destinationPath: "s3://bykaj-cloudnative-pg"
    endpointURL: "https://s3.us-west-001.backblazeb2.com"
    s3Credentials:
      accessKeyId:
        name: &secret cloudnative-pg-secret
        key: B2_KEY_ID
      secretAccessKey:
        name: *secret
        key: B2_APPLICATION_KEY
    wal:
      compression: bzip2
      maxParallel: 8
  retentionPolicy: 30d
