---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crd-schema-publisher
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: crd-schema-publisher-secret
    creationPolicy: Owner
    template:
      data:
        CLOUDFLARE_ACCOUNT_ID: "{{ .CF_ACCOUNT_ID }}"
        CLOUDFLARE_API_TOKEN: "{{ .CF_API_TOKEN_K8SSCHEMAS }}"
  dataFrom:
    - extract:
        key: cloudflare
      rewrite: [{regexp: {source: (.*), target: CF_$1}}]
