---
# yaml-language-server: $schema=https://schemas.bykaj.io/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: configarr
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: configarr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SABNZBD_API_KEY: "{{ .SN_SABNZBD_API_KEY }}"
        SONARR_API_KEY: "{{ .SR_SONARR_API_KEY }}"
        RADARR_API_KEY: "{{ .RR_RADARR_API_KEY }}"
        WHISPARR_API_KEY: "{{ .WR_WHISPARR_API_KEY }}"
  dataFrom:
    - extract:
        key: sabnzbd
      rewrite: [{regexp: {source: (.*), target: SN_$1}}]
    - extract:
        key: sonarr
      rewrite: [{regexp: {source: (.*), target: SR_$1}}]
    - extract:
        key: radarr
      rewrite: [{regexp: {source: (.*), target: RR_$1}}]
    - extract:
        key: whisparr
      rewrite: [{regexp: {source: (.*), target: WR_$1}}]