---
# yaml-language-server: $schema=https://schemas.bykaj.io/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda
spec:
  chartRef:
    kind: OCIRepository
    name: keda
  interval: 1h
  values:
    enableServiceLinks: false
    prometheus:
      metricServer:
        enabled: true
        serviceMonitor:
          enabled: true
      operator:
        enabled: true
        serviceMonitor:
          enabled: true
      webhooks:
        enabled: true
        serviceMonitor:
          enabled: true
    # resources:
    #   operator:
    #     requests:
    #       cpu: 10m
    #       memory: 128Mi
    #     limits:
    #       memory: 256Mi
    #   metricServer:
    #     requests:
    #       cpu: 10m
    #       memory: 128Mi
    #     limits:
    #       memory: 128Mi
    #   webhooks:
    #     requests:
    #       cpu: 10m
    #       memory: 128Mi
    #     limits:
    #       memory: 128Mi
