---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../components/namespace
replacements:
  - path: ../../components/replacements/ks.yaml
resources:
  #- ./blackbox-exporter/ks.yaml
  - ./fluent-bit/ks.yaml
  - ./gatus/ks.yaml
  - ./goldilocks/ks.yaml
  - ./grafana/ks.yaml
  - ./kromgo/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./kube-state-metrics/ks.yaml
  - ./node-exporter/ks.yaml
  - ./robusta/ks.yaml
  - ./silence-operator/ks.yaml
  - ./unpoller/ks.yaml
  - ./victoria-logs/ks.yaml
