---
# yaml-language-server: $schema=https://schemas.bykaj.io/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: dockerhub-rules
  labels:
    prometheus: k8s
    role: alert-rules
spec:
  groups:
    - name: dockerhub
      rules:
        - alert: DockerhubRateLimitRisk
          annotations:
            summary: There are {{ $value }} containers pulling from Dockerhub. This may lead to rate limiting.
          expr: count(time() - container_last_seen{image=~"(docker.io).*",container!=""} < 30) > 100
          labels:
            severity: critical
