---
ingress:
  - &config
    hostname: "bykaj.app"
    originRequest:
      http2Origin: true
      keepAliveTimeout: 3600s
      originServerName: "external.bykaj.app"
      tcpKeepAlive: 7200s
    service: https://envoy-external.network.svc.cluster.local
  - <<: *config
    hostname: "*.bykaj.app"
  - <<: *config
    hostname: "bykaj.dev"
  - <<: *config
    hostname: "*.bykaj.dev"
  - <<: *config
    hostname: "cetana.id"
  - <<: *config
    hostname: "*.cetana.id"
  - <<: *config
    hostname: "bykaj.io"
  - <<: *config
    hostname: "*.bykaj.io"
  - <<: *config
    hostname: "drup.lol"
  - <<: *config
    hostname: "*.drup.lol"
  - <<: *config
    hostname: "kaj.pics"
  - <<: *config
    hostname: "*.kaj.pics"
  - service: http_status:404
