---
# yaml-language-server: $schema=https://schemas.bykaj.io/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopiur-replication
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: kopiur-replication-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        B2_KEY_ID: "{{ .S3_ACCESS_KEY_ID }}"
        B2_KEY: "{{ .S3_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: kopiur
---
# yaml-language-server: $schema=https://schemas.bykaj.io/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nas-kopia-ui
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: nas-kopia-ui-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .KOPIA_UI_USERNAME }}"
        password: "{{ .KOPIA_UI_PASSWORD }}"
  dataFrom:
    - extract:
        key: kopiur
