---
# yaml-language-server: $schema=https://schemas.bykaj.io/litellm.home-operations.com/litellmmodel_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: minimax-m2-7-anthropic
spec:
  info:
    extra:
      supports_reasoning: true
    maxInputTokens: 192000
    maxOutputTokens: 16384
    maxTokens: 204800
    supportsFunctionCalling: true
    supportsPromptCaching: true
  modelName: minimax/MiniMax-M2-7-anthropic
  params:
    apiBase: https://api.minimax.io/anthropic
    apiKeyRef:
      key: MINIMAX_API_KEY
      name: litellm-secret
    dropParams: true
    model: anthropic/MiniMax-M2.7
