---
# yaml-language-server: $schema=https://schemas.bykaj.io/litellm.home-operations.com/litellmmodel_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: minimax-m3
spec:
  info:
    extra:
      supports_reasoning: true
    maxInputTokens: 1000000
    maxOutputTokens: 131072
    maxTokens: 1000000
    supportsFunctionCalling: true
    supportsPromptCaching: true
    supportsVision: true
  modelName: minimax/MiniMax-M3
  params:
    additional:
      extra_body:
        reasoning_split: true
    apiBase: https://api.minimax.io/v1
    apiKeyRef:
      key: MINIMAX_API_KEY
      name: litellm-secret
    model: minimax/MiniMax-M3
