---
# yaml-language-server: $schema=https://schemas.bykaj.io/litellm.home-operations.com/litellmmodel_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: minimax-m2-7
spec:
  info:
    extra:
      supports_reasoning: true
    maxInputTokens: 192000
    maxOutputTokens: 16384
    maxTokens: 204800
    supportsFunctionCalling: true
  modelName: minimax/MiniMax-M2-7
  params:
    additional:
      extra_body:
        reasoning_split: true
    apiBase: https://api.minimax.io/v1
    apiKeyRef:
      key: MINIMAX_API_KEY
      name: litellm-proxy-secret
    model: minimax/MiniMax-M2.7
