---
# yaml-language-server: $schema=https://schemas.bykaj.io/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app wastebin
spec:
  chartRef:
    kind: OCIRepository
    name: wastebin
  interval: 1h
  values:
    controllers:
      wastebin:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/quxfoo/wastebin
              tag: 3.3.0@sha256:b93714fe28ddf15848fa92c44ec666f7c66907f7495740d18b5eaa07cfd8c0ae
            env:
              TMPDIR: "/tmp"
              TZ: "${TIMEZONE}"
              WASTEBIN_ADDRESS_PORT: "0.0.0.0:8088"
              WASTEBIN_BASE_URL: "https://${DOMAIN_LOL}/"
              WASTEBIN_DATABASE_PATH: "/data/state.db"
              WASTEBIN_MAX_BODY_SIZE: "5242880" # 5Mb
              WASTEBIN_PASTE_EXPIRATIONS: "10m,1h,1d,1w=d,1M,1y,0"
              WASTEBIN_THEME: "onehalf"
              WASTEBIN_TITLE: "drupLOL"
            envFrom:
              - secretRef:
                  name: wastebin-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 8088
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 5m
                memory: 128Mi
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        fsGroupChangePolicy: OnRootMismatch
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: "Tools"
          gethomepage.dev/name: "${APP_NAME}"
          gethomepage.dev/icon: "sh-wastebin.svg"
        hostnames:
          - "${APP_DOMAIN:=${APP_SUBDOMAIN:=${APP}}.${DOMAIN_APP}}"
        parentRefs:
          - name: envoy-external
            namespace: network
    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /data
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
