---
# yaml-language-server: $schema=https://schemas.bykaj.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app whisparr
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/keda/nfs-scaler
    - ../../../../components/volsync
  dependsOn:
    - name: prowlarr
    - name: sabnzbd
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: ./kubernetes/apps/downloads/whisparr/app
  postBuild:
    substitute:
      APP: *app
      APP_GID: "4000"
      APP_UID: "4000"
      APP_NAME: Whisparr
      VOLSYNC_CACHE_CAPACITY: 5Gi
      VOLSYNC_CAPACITY: 20Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
