---
# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
version: 1
metadata:
  name: Cetana ID - Password change flow
entries:
- attrs:
    check_static_rules: true
    check_zxcvbn: true
    length_min: 8
    password_field: password
    zxcvbn_score_threshold: 2
    error_message: Password needs to be 8 characters or longer.
  identifiers:
    name: cetana-password-change-password-policy
  model: authentik_policies_password.passwordpolicy
  id: cetana-password-change-password-policy
- attrs:
    designation: stage_configuration
    name: Change Password
    title: Change password
    authentication: require_authenticated
  identifiers:
    slug: cetana-password-change
  model: authentik_flows.flow
  id: flow
- attrs:
    order: 300
    placeholder: Password
    placeholder_expression: false
    required: true
    type: password
    field_key: password
    label: Password
  identifiers:
    name: cetana-password-change-field-password
  id: prompt-field-password
  model: authentik_stages_prompt.prompt
- attrs:
    order: 301
    placeholder: Password (repeat)
    placeholder_expression: false
    required: true
    type: password
    field_key: password_repeat
    label: Password (repeat)
  identifiers:
    name: cetana-password-change-field-password-repeat
  id: prompt-field-password-repeat
  model: authentik_stages_prompt.prompt
- attrs:
    fields:
    - !KeyOf prompt-field-password
    - !KeyOf prompt-field-password-repeat
    validation_policies:
    - !KeyOf cetana-password-change-password-policy
  identifiers:
    name: cetana-password-change-prompt
  id: cetana-password-change-prompt
  model: authentik_stages_prompt.promptstage
- identifiers:
    name: cetana-password-change-write
  id: cetana-password-change-write
  model: authentik_stages_user_write.userwritestage
  attrs:
    user_creation_mode: never_create
- identifiers:
    order: 0
    stage: !KeyOf cetana-password-change-prompt
    target: !KeyOf flow
  model: authentik_flows.flowstagebinding
- identifiers:
    order: 1
    stage: !KeyOf cetana-password-change-write
    target: !KeyOf flow
  model: authentik_flows.flowstagebinding
