---
# yaml-language-server: $schema=https://schemas.bykaj.io/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: open-webui-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        KAGI_SEARCH_API_KEY: "{{ .OW_KAGI_SEARCH_API_KEY }}"
        OAUTH_CLIENT_ID: "{{ .OW_OAUTH_CLIENT_ID }}"
        OAUTH_CLIENT_SECRET: "{{ .OW_OAUTH_CLIENT_SECRET }}"
        WEBUI_SECRET_KEY: "{{ .OW_WEBUI_SECRET_KEY }}"
        WEBSOCKET_REDIS_URL: "redis://:{{ .DF_DRAGONFLY_PASSWORD }}@${REDIS_HOST}:6379/7"
  dataFrom:
    - extract:
        key: open-webui
      rewrite: [{ regexp: { source: (.*), target: OW_$1 } }]
    - extract:
        key: dragonfly
      rewrite: [{ regexp: { source: (.*), target: DF_$1 } }]
