---
# yaml-language-server: $schema=https://schemas.bykaj.io/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: windshift
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: windshift-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SSO_SECRET: "{{ .WS_SSO_SECRET }}"
  dataFrom:
    - extract:
        key: windshift
      rewrite: [{ regexp: { source: (.*), target: WS_$1 } }]
