---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
components:
  - ../../components/namespace
replacements:
  - path: ../../components/replacements/ks.yaml
resources:
  - ./certificates/ks.yaml
  - ./cloudflare-tunnel/ks.yaml
  - ./echo-server/ks.yaml
  - ./envoy-gateway/ks.yaml
  - ./external-dns/ks.yaml
  - ./external-services/ks.yaml
  - ./k8s-gateway/ks.yaml
  - ./tailscale-operator/ks.yaml
  - ./whoami/ks.yaml
