---
# yaml-language-server: $schema=https://schemas.bykaj.io/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-proxy
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: litellm-proxy-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        LITELLM_MASTER_KEY: "{{ .LL_LITELLM_MASTER_KEY }}"
        REDIS_URL: "redis://:{{ .DF_DRAGONFLY_PASSWORD }}@${REDIS_HOST}:6379/6"
  dataFrom:
    - extract:
        key: litellm
      rewrite: [{ regexp: { source: (.*), target: LL_$1 } }]
    - extract:
        key: dragonfly
      rewrite: [{ regexp: { source: (.*), target: DF_$1 } }]
